#!/bin/sh
# Convert jpeg/png/gif file to pdf only when the source is younger than destination

# $0 : command scrift file name
# $1 : source file path
# $2 : destination file path


# "convert" is a command of the ImageMagick
# if the source is younger than destination or destination doesn't exist
if [ $1 -nt $2 ] || [ ! -e $2 ]; then  
    # Picture like jpg, png or gif? 
    if [ "${1##*.}" = "jpg" ] || [ "${1##*.}" = "png" ] ||[ "${1##*.}" = "gif" ]; then
        convert $1 $2  # Convert it 
    fi

    # Drawing by drawio? 
    # Crop the drawing with 10pt margin. 
    if [ "${1##*.}" = "drawio" ]; then
        echo "drawio -xf pdf --crop -b 10 -o" 1>&2
        drawio -xf pdf --crop -b 10 -o  $2 $1 # Convert it
    fi

    # Is PDF? 
    if [ "${1##*.}" = "pdf" ]; then
        cp $1 $2 # Convert it
    fi


fi