#!/bin/sh
# Convert jpeg/png/gif file to pdf only when the source is younger than destination

# $0 : command scrift file name
# $1 : source file path
# $2 : destination file path


# "convert" is a command of the ImageMagick
# if the source is younger than destination or destination doesn't exist
if [ $1 -nt $2 ] || [ ! -e $2 ]; then  
    convert $1 $2  # Convert it 
fi